/**
 * OpenAPI to TypeScript types generator.
 *
 * Generates TypeScript interfaces from OpenAPI 3.x schemas.
 * Supports both local fixture files and remote URLs.
 *
 * Usage:
 *   pnpm gen:types              # Generate from default URL or fixture
 *   pnpm gen:types --check      # Check for drift (exit non-zero if stale)
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Default configuration
const DEFAULT_OPENAPI_URL = "http://localhost:8000/openapi.json";
const DEFAULT_FIXTURE_PATH = resolve(__dirname, "./fixtures/openapi.json");
const OUTPUT_PATH = resolve(
  __dirname,
  "../../../packages/api-client/src/types/generated.ts"
);

/**
 * Convert OpenAPI schema type to TypeScript type
 */
function openApiTypeToTs(
  schema: Record<string, unknown>,
  required: string[]
): string {
  if (!schema || typeof schema !== "object") {
    return "unknown";
  }

  const type = schema.type as string | undefined;
  const format = schema.format as string | undefined;
  const ref = schema.$ref as string | undefined;
  const nullable = schema.nullable === true;
  const enumValues = schema.enum as unknown[] | undefined;

  // Handle $ref (reference to another schema)
  if (ref) {
    const name = ref.split("/").pop() || ref;
    const tsType = name.replace(/^#\/components\/schemas\//, "");
    return nullable ? `${tsType} | null` : tsType;
  }

  // Handle enum
  if (enumValues) {
    const enumTs = enumValues
      .map((v) => (typeof v === "string" ? `"${v}"` : v))
      .join(" | ");
    return nullable ? `(${enumTs}) | null` : enumTs;
  }

  // Handle arrays
  if (type === "array") {
    const items = schema.items as Record<string, unknown> | undefined;
    const itemType = items
      ? openApiTypeToTs(items, required)
      : "unknown";
    return nullable ? `(${itemType}[]) | null` : `${itemType}[]`;
  }

  // Handle objects
  if (type === "object" || schema.properties) {
    // If it has properties, it's an inline object definition
    if (schema.properties) {
      const props = schema.properties as Record<string, Record<string, unknown>>;
      const requiredProps = (schema.required as string[]) || [];
      const propsTs = Object.entries(props)
        .map(([name, prop]) => {
          const isRequired = requiredProps.includes(name);
          const propType = openApiTypeToTs(prop, requiredProps);
          return `  ${name}${isRequired ? "" : "?"}: ${propType};`;
        })
        .join("\n");
      const result = `{\n${propsTs}\n}`;
      return nullable ? `(${result}) | null` : result;
    }
    return nullable ? "Record<string, unknown> | null" : "Record<string, unknown>";
  }

  // Handle primitive types
  switch (type) {
    case "integer":
    case "number":
      return nullable ? "number | null" : "number";
    case "boolean":
      return nullable ? "boolean | null" : "boolean";
    case "string":
      // Handle date-time format
      if (format === "date-time" || format === "date") {
        return nullable ? "string | null" : "string";
      }
      if (format === "uuid") {
        return nullable ? "string | null" : "string";
      }
      return nullable ? "string | null" : "string";
    default:
      return "unknown";
  }
}

/**
 * Generate TypeScript interfaces from OpenAPI components/schemas
 */
function generateInterfaces(schemas: Record<string, Record<string, unknown>>): string {
  const interfaces: string[] = [];

  for (const [name, schema] of Object.entries(schemas)) {
    // Skip internal schemas
    if (name.startsWith("_")) continue;

    const required = (schema.required as string[]) || [];
    const properties = (schema.properties as Record<string, Record<string, unknown>>) || {};

    const propsTs = Object.entries(properties)
      .map(([propName, propSchema]) => {
        const isRequired = required.includes(propName);
        const propType = openApiTypeToTs(propSchema, required);
        return `  ${propName}${isRequired ? "" : "?"}: ${propType};`;
      })
      .join("\n");

    interfaces.push(`export interface ${name} {\n${propsTs}\n}`);
  }

  return interfaces.join("\n\n");
}

/**
 * Generate TypeScript types from OpenAPI JSON
 */
export function generateTypes(openapiJson: Record<string, unknown>): string {
  const components = (openapiJson.components as Record<string, unknown>) || {};
  const schemas = (components.schemas as Record<string, Record<string, unknown>>) || {};

  const interfaces = generateInterfaces(schemas);

  const header = `/**
 * Auto-generated TypeScript types from OpenAPI schema.
 * DO NOT EDIT - This file is generated by scripts/generate-types.ts
 *
 * To regenerate: pnpm --filter web-pwa gen:types
 */

`;

  return header + interfaces;
}

/**
 * Fetch OpenAPI JSON from URL
 */
async function fetchOpenApi(url: string): Promise<Record<string, unknown>> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }
  return response.json() as Promise<Record<string, unknown>>;
}

/**
 * Main function to run the generator
 */
async function main() {
  const args = process.argv.slice(2);
  const checkMode = args.includes("--check");

  let openapiJson: Record<string, unknown>;

  // Determine source: URL or fixture
  const urlArg = args.find((a) => a.startsWith("--url="));
  if (urlArg) {
    const url = urlArg.replace("--url=", "");
    console.log(`Fetching OpenAPI from: ${url}`);
    openapiJson = await fetchOpenApi(url);
  } else if (existsSync(DEFAULT_FIXTURE_PATH)) {
    console.log(`Using fixture: ${DEFAULT_FIXTURE_PATH}`);
    openapiJson = JSON.parse(readFileSync(DEFAULT_FIXTURE_PATH, "utf-8"));
  } else if (existsSync(DEFAULT_OPENAPI_URL.replace("http://localhost:8000", ""))) {
    // Fallback: try local file
    console.log(`Using local file: ${DEFAULT_OPENAPI_URL}`);
    openapiJson = JSON.parse(readFileSync(DEFAULT_OPENAPI_URL, "utf-8"));
  } else {
    console.log(`Using fixture: ${DEFAULT_FIXTURE_PATH}`);
    openapiJson = JSON.parse(readFileSync(DEFAULT_FIXTURE_PATH, "utf-8"));
  }

  // Generate types
  const generated = generateTypes(openapiJson);

  // Check mode: compare with existing file
  if (checkMode) {
    if (!existsSync(OUTPUT_PATH)) {
      console.error("ERROR: Generated types file does not exist. Run without --check first.");
      process.exit(1);
    }
    const existing = readFileSync(OUTPUT_PATH, "utf-8");
    if (existing.trim() !== generated.trim()) {
      console.error("ERROR: Generated types differ from existing file. Run 'pnpm gen:types' to update.");
      process.exit(1);
    }
    console.log("Types are up to date.");
    process.exit(0);
  }

  // Write output
  writeFileSync(OUTPUT_PATH, generated, "utf-8");
  console.log(`Generated types written to: ${OUTPUT_PATH}`);
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
