/**
 * Auto-generated TypeScript types from OpenAPI schema.
 * DO NOT EDIT - This file is generated by scripts/generate-types.ts
 *
 * To regenerate: pnpm --filter web-pwa gen:types
 */

export interface FacilityOut {
  id: string;
  tenant_id: string;
  name: string;
  slug: string;
  address_line1: string;
  address_line2?: string | null;
  city: string;
  state: string;
  postal_code: string;
  country: string;
  timezone: string;
  phone?: string | null;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface FacilityListResponse {
  data: FacilityOut[];
}

export interface ResourceOut {
  id: string;
  tenant_id: string;
  facility_id: string;
  name: string;
  slug: string;
  resource_type: string;
  capacity: number;
  attributes: Record<string, unknown>;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface ResourceListResponse {
  data: ResourceOut[];
}

export interface BookingOut {
  id: string;
  tenant_id: string;
  customer_id: string;
  resource_id: string;
  facility_name?: string | null;
  resource_name?: string | null;
  start_at: string;
  end_at: string;
  status: string;
  price_cents: number;
  currency: string;
  notes?: string | null;
  cancellation_reason?: string | null;
  cancelled_at?: string | null;
  checked_in_at?: string | null;
  completed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface BookingListResponse {
  data: BookingOut[];
}
